"""initial migration

Revision ID: 75c4c24f0fca
Revises: 7f8f4cd7737e
Create Date: 2023-11-28 21:26:07.409617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c4c24f0fca'
down_revision: Union[str, None] = '7f8f4cd7737e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
