"""on delete and on update logic added to basket item

Revision ID: f1eeefab60fe
Revises: 034c4224c778
Create Date: 2023-12-04 00:03:34.299765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1eeefab60fe'
down_revision: Union[str, None] = '034c4224c778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('basket_item_user_id_fkey', 'basket_item', type_='foreignkey')
    op.drop_constraint('basket_item_product_id_fkey', 'basket_item', type_='foreignkey')
    op.create_foreign_key(None, 'basket_item', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'basket_item', 'product', ['product_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'basket_item', type_='foreignkey')
    op.drop_constraint(None, 'basket_item', type_='foreignkey')
    op.create_foreign_key('basket_item_product_id_fkey', 'basket_item', 'product', ['product_id'], ['id'])
    op.create_foreign_key('basket_item_user_id_fkey', 'basket_item', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
